/* Table talk content. Two speakers, A and B. One session at a time, six
   positions: levels 5, 6, 7, 8, 9, 10, 11.

   Line shape: [speaker, text, notes]
     text   mark the words that count with {L|…} {I|…} {P|…}
            L = Listening, I = Interacting, P = Presenting (the three rubric rows)
     notes  { L: [level, why], I: [level, why], P: [level, why] }
            the level is the continuum level those words are evidence for,
            which is not always the level of the conversation. */

const SESSIONS = [
  {
    n: 1, title: "Personal response", label: "Session 1 · Table 4 · Chapter 37",
    prompt: "I do not tell lies. Mother used to say that this was because I was a good person. But it is not because I am a good person. It is because I can't tell lies.",
    task: "A feeling and a reason each. Then respond to each other.",
    levels: [
      { level: 5, band: "Working towards", lines: [
        ["A", "{P|reads the quote, quietly} {I|I think he's a good person, because he doesn't lie.}",
          { P: [5, "Read to the table so the talk can start."], I: [5, "A point of view with a reason. Level 5."] }],
        ["B", "I think it's sad.", {}],
        ["A", "{L|Why sad?}", { L: [5, "A clarifying question."] }],
        ["B", "{I|Because he can't help it. It's not a choice for him.}", { I: [5, "Now a reason with the point of view."] }],
        ["A", "{L|What do you mean, not a choice?}", { L: [5, "Asks B to say what they mean."] }],
        ["B", "Like his mum thinks he's being good but he just can't lie.", {}],
        ["A", "{P|reads the last line again} Okay. Write that?", { P: [5, "Reads to the table. Then the talk ends."] }],
      ] },
      { level: 6, band: "Working towards", lines: [
        ["A", "{P|reads the quote to the table, looks up} {I|I think it's honest, because he says it's not about being good.}",
          { P: [6, "Read clearly to the small group."], I: [5, "A point of view with a reason from the quote."] }],
        ["B", "{L|So the main idea is he can't lie, not that he's good?}", { L: [6, "B describes the key idea in what A said."] }],
        ["A", "Yeah. {I|He's correcting his mum.}", { I: [5, "A point of view, short, with the reason already given."] }],
        ["B", "{I|Then it's a bit sad, because she wanted him to be good.}", { I: [7, "A feeling with a reason from the quote, shared into the discussion. Level 7 in a level 6 talk."] }],
        ["A", "{L|Sad for her, or for him?}", { L: [5, "A clarifying question."] }],
        ["B", "For her. He doesn't mind.", {}],
        ["A", "{I|True, he just says what's accurate.} {P|to the table} Everyone got that?", { I: [5, "Agrees with a reason."], P: [6, "Speaks to the whole table, not only to B."] }],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the quote fast, eyes on the page} {I|I think that's good, he doesn't lie.}",
          { P: [5, "Read to the table, but fast and eyes down: nothing in the voice helps B hear the quote."],
            I: [5, "A point of view is given with no reason. 'Good' gives B nothing to answer."] }],
        ["B", "{I|Yeah, same.} Lying's bad.",
          { I: [5, "Agreement without a reason of its own. The talk is still where A left it."] }],
        ["A", "{I|Like, if you never lie people trust you.}",
          { I: [5, "Now a reason. A has presented and justified a point of view, which is level 5."] }],
        ["B", "{L|Wait, what do you mean by trust?}",
          { L: [5, "A clarifying question. It gets A to say what a word means, which is level 5 listening."] }],
        ["A", "Like they know you won't make stuff up.", {}],
        ["B", "Okay. {I|I still reckon it's a bit sad though, his mum said he's good and he's like, no I'm not.}",
          { I: [7, "An interpretation with a reason from the quote, shared into the discussion. This one line is level 7."] }],
        ["A", "{P|looks at the clock} Are we done?",
          { P: [6, "The body language says the talk is over. Two minutes in, because nobody built on B's idea."] }],
      ] },
      { level: 8, band: "Working towards", lines: [
        ["A", "{P|reads the quote, looks up} {I|I think it's a bit sad, because his mum's trying to be nice and he won't take it.}",
          { P: [6, "Read clearly to B, with a look up at the end. Enough to start the talk."],
            I: [7, "A feeling with a reason from the quote. An interpretation, shared."] }],
        ["B", "{I|I didn't think sad, I thought it was kind of funny. He's so literal.}",
          { I: [7, "A different feeling with its own reason. B is responding to the quote, not yet to A."] }],
        ["A", "{L|So you reckon he doesn't get that she's being kind?}",
          { L: [8, "A says back what B implied but did not say. Interpreting implied meaning is level 8."] }],
        ["B", "Yeah, or he gets it and doesn't care. {I|He just wants it to be accurate.}",
          { I: [7, "B sharpens their own idea in answer to A's question."] }],
        ["A", "{I|That's what makes it sad for me though. He'd rather be accurate than let her be nice.}",
          { I: [7, "A links B's word 'accurate' back to their own feeling. The two readings are now touching."] }],
        ["B", "{L|Okay. What was the other question, is there a kind lie?}",
          { L: [6, "B moves the talk on to the next key idea instead of taking A's point further. That is the line this table does not cross."] }],
        ["A", "{I|I reckon yes. Like saying you love a present.}",
          { I: [5, "A point of view with an example from life, not yet tied back to the quote."] }],
        ["B", "{I|He'd say that's still a lie though.} {P|shrugs} Should we write that down?",
          { I: [7, "B answers from Christopher's point of view. Then the talk stops rather than deciding anything."],
            P: [6, "The shrug hands the decision to the paper instead of to A."] }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads slowly, looks up at the end} {I|My first reaction is that it's a bit sad, because he's correcting his own mum: 'it is not because I am a good person'.}",
          { P: [7, "Slowing down and looking up at the end uses voice and body to hand the quote to B."],
            I: [7, "A feeling, a reason, and the words it comes from. This is what a shared interpretation looks like."] }],
        ["B", "{L|So you think he's rejecting her?} {I|I thought it was funny, the way he splits hairs. Good person versus can't tell lies.}",
          { L: [8, "B says back what A implied but did not say, then checks it. Interpreting implied meaning is level 8."],
            I: [7, "B disagrees with the feeling, not with A, and gives the reason in the same breath."] }],
        ["A", "{L|Funny on purpose, or just funny to us?}",
          { L: [8, "A separates two meanings B ran together. The question sharpens B's idea rather than attacking it."] }],
        ["B", "To us. He's dead serious. {I|And that's what makes it a bit sad as well, so I partly agree with you.}",
          { I: [7, "B answers, then links back to A's feeling. Two responses have become one conversation."] }],
        ["A", "{I|And 'I can't' means he never has to decide. I'd find that easier.}",
          { I: [7, "A adds a new reading and links it to their own life. The link comes straight back to the quote."] }],
        ["B", "{L|Say more about 'easier'?}",
          { L: [7, "Active listening: B keeps A's best idea alive by asking for more instead of moving on."] }],
        ["A", "We lie to be polite. He'd just tell you the true thing about your haircut.", {}],
        ["B", "{I|I see it differently, because the stress just moves onto everyone else.} {P|pauses} So, a strength and a problem?",
          { I: [9, "Disagreement said as 'I see it differently, because'. The voice is changed to discuss, not to win."],
            P: [7, "The pause before the question gives A room to answer instead of filling the silence."] }],
      ] },
      { level: 10, band: "Above", lines: [
        ["A", "{P|reads slowly, stressing 'can't'} {I|It's a bit sad for me. She's trying to be nice about it and he won't let her. 'It is because I can't tell lies.'}",
          { P: [9, "The stress on 'can't' is a change of voice made to carry the reading."],
            I: [7, "A feeling with the reason and the words it lives in."] }],
        ["B", "{L|So you think he's correcting her?}",
          { L: [8, "B says back what A implied and checks it before answering."] }],
        ["A", "Yeah. {I|How did it hit you?}",
          { I: [10, "A hands the floor over with a direct question. Inclusive language that keeps B in the talk."] }],
        ["B", "{I|I thought it was funny, because he's splitting hairs. I get the sad bit too. But he'd say he's not correcting her, he's just being accurate.}",
          { I: [7, "B gives their own feeling, links to A's, and adds Christopher's likely view."] }],
        ["A", "{I|Yeah, for him true beats kind every time.} {L|Look at how it's written though. 'It is not because', 'It is because'. Same shape twice. It sounds like he's fixing a mistake.}",
          { I: [7, "A turns B's point into a rule for the character."],
            L: [10, "A analyses the language: a repeated sentence shape and the effect it has. Discussing the effects of language features in conversation is the level 10 line."] }],
        ["B", "{I|Yes, and that's why it reads as a correction. So both: it's a strength because he can't be fake, and a problem because he can't be gentle.}",
          { I: [9, "B builds on A's language point to settle the question the prompt asked. The register shifts from chat to conclusion."] }],
        ["A", "{I|I'd go with that.} {P|checks B is ready before moving on} Want to write 'true beats kind' as our one thing?",
          { I: [10, "Agreement offered as a shared wording, then a check before the pair moves on."],
            P: [8, "A waits for B rather than talking over the write-up."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads it twice, the second time stressing 'can't'} {I|It feels lonely to me. 'I can't' is the only reason he gives, and his mum's nicer version just gets crossed out.}",
          { P: [9, "Re-reading with a different stress is a change of voice used to make an argument."],
            I: [7, "The reason is built from a single stressed word and a contrast between two reasons in the quote."] }],
        ["B", "{L|So you think he'd rather be right than be called good?}",
          { L: [8, "B paraphrases A's idea back as a question to test it. Inferring what A implies, then checking."] }],
        ["A", "Yeah. Right about himself, even if it makes him look worse.", {}],
        ["B", "{I|I'd push back on that. He's not saying he isn't good, he just can't take a reason that isn't true. That's probably the most honest thing in the whole book.}",
          { I: [9, "B disagrees with A's reading, not A's feeling, and offers a rival reading of the same words."] }],
        ["A", "{L|What about the white lies though?} {I|Later on he says a white lie is just leaving stuff out, and he's fine with that. So he does bend it.}",
          { L: [9, "A listens critically: B's claim is tested against a second passage, not just accepted."],
            I: [7, "A counters with evidence from another part of the novel."] }],
        ["B", "{L|Which chapter, roughly?}",
          { L: [9, "B asks for the location so the evidence can be checked, not taken on trust."] }],
        ["A", "The definition's right after this, chapter 37. The white lie bit is a few chapters later. {P|reads two lines}",
          { P: [8, "Reading the lines aloud puts the evidence in front of B clearly enough to argue with."] }],
        ["B", "{I|Okay, that changes my mind. 'Leaving things out' is what his dad does about his mum. So Christopher's own rule lets in the biggest lie in the book.} {P|slows right down for the last sentence} Can we write that down as our one thing?",
          { I: [10, "B revises out loud and turns the talk into a shared product. Building on and refining ideas in response to a peer is the Listening 11 line too."],
            P: [9, "Slowing down for the sentence that matters suits the purpose: this is the line to write down."] }],
      ] },
    ],
  },

  {
    n: 2, title: "I couldn't disagree more", label: "Session 2 · Table 1",
    prompt: "Ed Boone is a good father.",
    task: "Take a side with a reason from the book. Quote the other person back before you answer them.",
    levels: [
      { level: 5, band: "Working towards", lines: [
        ["A", "{P|reads the statement}", { P: [5, "Read to the table."] }],
        ["B", "{I|Disagree. He killed Wellington.}", { I: [5, "A side and a reason."] }],
        ["A", "{I|Agree. He cooks for him and stuff.}", { I: [5, "A side and a reason, vague."] }],
        ["B", "{L|Cooks for who?}", { L: [5, "A clarifying question."] }],
        ["A", "Christopher. He makes his dinner every night.", {}],
        ["B", "{I|Still killed a dog though.}", { I: [5, "Repeats the side and the reason."] }],
        ["A", "Yeah.", {}],
        ["B", "So we disagree.", {}],
      ] },
      { level: 6, band: "Working towards", lines: [
        ["A", "{P|reads the statement clearly, to both} Who's first?", { P: [6, "Read clearly to the small group, then hands out the first turn."] }],
        ["B", "{I|Disagree, because he killed Wellington and lied about Mother.}", { I: [5, "A side with two reasons."] }],
        ["A", "{L|So your main reason is the lying?}", { L: [6, "A picks out the key idea in what B said."] }],
        ["B", "Both. The dog and the lying.", {}],
        ["A", "{I|Agree, because he looks after Christopher every day. The food, the school, the police station.}", { I: [5, "A side with reasons from the book."] }],
        ["B", "{L|Wait, the police station?}", { L: [5, "A clarifying question."] }],
        ["A", "He comes and gets him out, in the first chapters.", {}],
        ["B", "{I|Okay, he does look after him. I still say the lie is too big.}", { I: [6, "B changes what they say to A after hearing the reason, and keeps the side. Level 6."] }],
        ["A", "{P|to the table} So one each way.", { P: [6, "Speaks to the whole table."] }],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the statement} {I|No way. He killed the dog.}",
          { P: [6, "Read clearly enough for B to answer."],
            I: [5, "A side and a reason in five words. It is a start."] }],
        ["B", "{I|I dunno, he does look after him though.}",
          { I: [5, "A different side with a reason, but 'looks after' is vague. A cannot quote it back because there is nothing specific in it."] }],
        ["A", "But he killed a dog with a garden fork!",
          { }],
        ["B", "{L|Yeah but that's one thing.}",
          { L: [6, "B has heard A's key idea and repeats it, but does not say what it weighs against."] }],
        ["A", "{I|It's a big thing.}",
          { I: [5, "A repeats their own point louder instead of answering B's. Nobody has quoted anyone."] }],
        ["B", "{P|shrugs} I guess.",
          { P: [6, "B gives up a real position with body language, because nobody asked for the evidence behind it."] }],
      ] },
      { level: 8, band: "Working towards", lines: [
        ["A", "{P|reads the statement} {I|I disagree. He killed Wellington and lied about it for ages.}",
          { P: [6, "Read clearly enough for B to answer."],
            I: [7, "A side with two reasons from the book."] }],
        ["B", "{I|I sort of agree though. He does everything for Christopher, like the food and the school stuff.}",
          { I: [7, "The other side, with reasons, though 'everything' is doing a lot of work."] }],
        ["A", "{L|You said 'everything', but he also lied about his mum being dead.}",
          { L: [7, "A picks up B's word and answers it. Active listening, one step short of quoting the whole claim back."] }],
        ["B", "{I|Yeah okay, that's really bad. But he did it because he thought it'd be easier for Christopher.}",
          { I: [7, "B concedes the lie and offers Father's reason for it. The concession is not used to restate a position."] }],
        ["A", "{I|Easier for him, more like.}",
          { I: [5, "An opinion with no evidence behind it. The book has the confession scene; A does not reach for it."] }],
        ["B", "{L|Maybe both?} {I|So he's a good dad who did a bad thing?}",
          { L: [8, "B hears that A and B are not actually opposed and says the middle out loud."],
            I: [7, "A shared position, reached quickly and without testing it."] }],
        ["A", "{P|nods} Yeah, put that.",
          { P: [6, "Agreement by nod. The talk ends two minutes early because nobody asked what would prove it."] }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads the statement, looks up} {I|I couldn't disagree more. He killed a dog with a garden fork and told his son the mother was dead.}",
          { P: [7, "Looking up after the statement invites the answer."],
            I: [7, "A side and two reasons from the book in one breath."] }],
        ["B", "{I|I'm going to agree, and I know that sounds bad. He cooks, he gets Christopher to school, he goes to the police station at one in the morning. The lie is terrible but the daily stuff is good fathering.}",
          { I: [7, "B takes the harder side and backs it with three concrete moments."] }],
        ["A", "{L|Do you mean good father overall, or good at the daily stuff? Because those aren't the same.}",
          { L: [8, "A splits 'good father' into two meanings B had run together. The argument now has somewhere to go."] }],
        ["B", "{I|Okay, good at the daily stuff. And I think that counts for more than one lie.}",
          { I: [9, "B concedes the distinction and restates the position inside it. Conceding is a change of voice, not a loss."] }],
        ["A", "{L|You said 'one lie'.} {I|It's every day for two years though. 'Your mother is dead', every day.}",
          { L: [9, "A quotes B's exact words back before answering them. That is critical listening: the answer is to what was actually said."],
            I: [7, "The counter is specific: the scale of the lie, in the book's own words."] }],
        ["B", "{I|Somewhere in the middle then. The 'you have to learn to trust me' scene is him trying,} {P|steady, not louder} but you can't order someone to trust you.",
          { I: [7, "B moves to a middle position and supports it with a line from the book."],
            P: [7, "The voice stays steady while disagreeing; volume is not the argument."] }],
        ["A", "{I|I'd go with 'a loving father who did something unforgivable'. Is that allowed as an answer?}",
          { I: [9, "A revises openly and offers a shared wording. The talk ends with a position, not a winner."] }],
      ] },
      { level: 10, band: "Above", lines: [
        ["A", "{P|reads the statement, then waits} {I|I'll start. I couldn't disagree more. Killing Wellington and then lying about Mother for two years isn't a good father, whatever else he does.}",
          { P: [8, "Read clearly, then a pause that gives B the chance to go first."],
            I: [7, "A side, two reasons, and a hedge that B can pick up."] }],
        ["B", "{L|'Whatever else he does' is doing a lot of work there.} {I|Because the whatever-else is every meal, every school run, the police station at one in the morning.}",
          { L: [9, "B quotes A's exact words back and answers those words, not a different claim."],
            I: [7, "Three concrete moments from the book."] }],
        ["A", "{I|Fair, I'll give you the daily stuff.} {L|But do you mean good father, or good at looking after him? I don't think they're the same.}",
          { I: [9, "A concedes out loud and keeps the argument."],
            L: [8, "A splits the statement into two meanings B had run together."] }],
        ["B", "{L|Look at how he says it when he confesses: 'I did it for the best'. He believes it. The book keeps giving him that line so we can't just hate him.}",
          { L: [10, "B analyses the effect of a repeated line on the reader. That is discussing the purpose of a language feature, the level 10 line."] }],
        ["A", "{I|Yes, and that's the point, the book wants us stuck.} {I|What would you need to see to call him good?}",
          { I: [10, "A builds on B, then asks B a question that keeps the talk open rather than closing it on A's side."] }],
        ["B", "{I|Him telling the truth without being caught. Which never happens. So: caring, but not good.}",
          { I: [9, "B names the evidence that would change their mind, checks the book for it, and states the position that follows."] }],
        ["A", "{I|I can live with 'caring but not good'.} {P|says it clearly, for the write-up}",
          { I: [9, "A accepts B's wording rather than restating their own."],
            P: [8, "The final wording is said clearly to the table, not muttered to the page."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads the statement} {L|Before we pick sides, what would count as evidence?}",
          { P: [8, "Read clearly to the table, then the floor is opened rather than filled."],
            L: [9, "A asks the pair to agree what would settle the question before anyone argues it."] }],
        ["B", "{I|What he does for Christopher, over time. Not what he meant to do. And on that he fails, because the lie about his mum is something he did every single day for two years.}",
          { I: [9, "B sets the test, then applies it. The side comes with the standard it was judged by."] }],
        ["A", "{L|'What he does over time', yeah, same test.} {I|But that also means the cooking, getting him to school, turning up at the police station at one in the morning, the swimming. So the real question is whether one massive thing cancels out a thousand small things.}",
          { L: [9, "A quotes B's test back and accepts it before disagreeing about what it shows."],
            I: [10, "A reframes the statement as a weighing problem the pair can actually decide. This is the Listening 10 line: analysing the purpose of the question."] }],
        ["B", "{I|I'll give you the thousand small things. But the small things are what a carer does. The big thing is what a liar does.}",
          { I: [9, "B concedes the whole of A's evidence and still counters, by changing what kind of thing each action is."] }],
        ["A", "{L|'Carer or liar' is saying he can only be one.} {I|But when he confesses he's both in the same speech. 'I did it for the best' and 'I killed Wellington' are like ten lines apart.}",
          { L: [9, "A quotes B's phrase and names the assumption inside it."],
            I: [7, "The counter is the passage that shows both things at once, located by its distance between two lines."] }],
        ["B", "{I|Okay, he's both. Then 'good father' is the wrong question. The real one is whether Christopher can ever trust him again, which is basically what the last chapters are about.}",
          { I: [10, "B concedes the reading and reframes toward the question the novel itself asks. Refining an idea in response to a peer is the Listening 12 line."] }],
        ["A", "{I|And the ending says he can do anything. It doesn't say he trusts his dad. That's not the same thing.} {P|lets that sit}",
          { I: [9, "A checks the shared position against the exact wording of the ending."],
            P: [9, "Silence used on purpose: the pause gives the last point its weight."] }],
        ["B", "So, not a good father, but maybe one Christopher can come back to. {L|Would you go with that?}",
          { L: [9, "B states the shared position and checks it is shared before it goes in the write-up."] }],
      ] },
    ],
  },

  {
    n: 3, title: "Passage analysis panel", label: "Session 3 · Table 1 · Chapter 2",
    prompt: "The opening: 'It was 7 minutes after midnight.' Christopher finds Wellington.",
    task: "What happens, how it is written, what it shows. Say 'yes, and'. Finish with the one thing you would tell the class.",
    levels: [
      { level: 5, band: "Working towards", lines: [
        ["A", "{P|reads the first page}", { P: [5, "Read to the table."] }],
        ["B", "{I|The dog's dead. It's got a fork in it.}", { I: [5, "Says what happens, from the page."] }],
        ["A", "{L|What's the time thing at the start?}", { L: [5, "A clarifying question."] }],
        ["B", "7 minutes after midnight.", {}],
        ["A", "{I|That's how it's written. Really exact.}", { I: [5, "An opinion about the writing."] }],
        ["B", "{I|And short sentences.}", { I: [5, "A second feature, named."] }],
        ["A", "What does it show?", {}],
        ["B", "{I|That he notices everything?}", { I: [5, "A guess at what it shows. Nobody takes it further."] }],
      ] },
      { level: 6, band: "Working towards", lines: [
        ["A", "{P|reads the first page, slowly enough to hear the sentences}", { P: [6, "Read clearly to the small group."] }],
        ["B", "{I|What happens: Christopher finds Wellington dead in the garden with a fork in him.}", { I: [5, "Answers the first question from the page."] }],
        ["A", "{L|And the main thing about how it's written is the time, 7 minutes after midnight?}", { L: [6, "A describes the key idea and checks it."] }],
        ["B", "Yeah. {I|Exact time, exact details. The fork, the grass.}", { I: [5, "Points at the words."] }],
        ["A", "{I|And the sentences are short. 'It was 7 minutes after midnight.' Full stop.}", { I: [5, "A feature with the words it lives in."] }],
        ["B", "{L|What does exact show, do you think?}", { L: [5, "A clarifying question that asks for the idea."] }],
        ["A", "{I|That he notices everything and doesn't say how he feels.}", { I: [7, "Feature to meaning. Level 7 in a level 6 talk."] }],
        ["B", "{P|to the table} So we say: exact details, no feelings. Everyone okay with that?", { P: [6, "Presents the table's one thing to the group."] }],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the first page, quickly} So he finds the dog and it's dead.",
          { P: [5, "Read to the table, but too fast for B to hear the sentences as sentences."] }],
        ["B", "{I|It says '7 minutes after midnight'. That's weird.}",
          { I: [5, "B points at words on the page and gives an opinion about them. 'Weird' is the start of a feature, not a description of one."] }],
        ["A", "{L|Yeah, it's like really specific.}",
          { L: [6, "A has heard B's key idea and nearly names the feature. 'Specific' needs a second sentence that never comes."] }],
        ["B", "And the dog's got a fork in it.", {}],
        ["A", "What do we write for the writing bit?", {}],
        ["B", "{I|Um, short sentences?}",
          { I: [5, "A real feature, guessed rather than pointed at. Nobody finds one."] }],
        ["A", "Okay, short sentences.",
          { }],
      ] },
      { level: 8, band: "Working towards", lines: [
        ["A", "{P|reads the first page} So he finds the dog, it's dead, and he hugs it. {I|It's weird how calm he is about it.}",
          { P: [6, "Read clearly to the table, a little fast."],
            I: [7, "What happens, then a first feature offered as a feeling: 'calm'."] }],
        ["B", "{I|Yeah, like '7 minutes after midnight'. Who says that?}",
          { I: [7, "B points at words on the page and reacts to them."] }],
        ["A", "{L|So the numbers make it calm?}",
          { L: [8, "A joins B's example to their own word. Inferring the link between two ideas is level 8."] }],
        ["B", "I think so. {I|And the sentences are really short. 'The dog was dead.'}",
          { I: [7, "A second feature, with the sentence that shows it."] }],
        ["A", "{I|So short sentences and numbers. It makes him sound like a robot.}",
          { I: [7, "A sums up the two features and names an effect. 'Robot' is an effect, but a rough one."] }],
        ["B", "{I|Not a robot, more like he's just reporting it.}",
          { I: [7, "B disagrees with the word, politely, and offers a better one."] }],
        ["A", "Okay, reporting. {P|writes} Feature: short sentences and numbers, makes it sound like a report.",
          { P: [6, "The one thing is said as it is written, to the page rather than to B. Nobody asks what the report is missing."] }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads the first page aloud, evenly} What happens is easy: he finds the dog, it's dead, there's a fork through it. {I|What's weird is how calm it is.}",
          { P: [7, "Reading evenly lets the flat tone of the page show. The voice is doing the analysis before the words do."],
            I: [7, "A answers the first panel question and offers the first feature for B to pick up."] }],
        ["B", "{L|Calm how? What makes it calm?}",
          { L: [7, "B refuses a vague word and asks A to say what makes it so. Active listening that improves the other person's idea."] }],
        ["A", "{I|'7 minutes after midnight', not 'just after midnight'. And the sentences are all short: 'The dog was dead.' Full stop.}",
          { I: [7, "A points at two things on the page: a number and a sentence length."] }],
        ["B", "{I|Yes, and there are no feeling words at all. He says the dog 'was not running or asleep', like he's ruling things out.}",
          { I: [7, "'Yes, and': B accepts A's features and adds a third, with its own quotation."] }],
        ["A", "{L|So the feature is short sentences plus exact numbers plus no emotion? That's three things. Do we pick one?}",
          { L: [8, "A joins the three observations into one claim and asks B to choose. Summarising what was said is listening for key ideas."] }],
        ["B", "{I|The numbers. '7 minutes' is the first thing on the page. It tells you how his head works before you even know his name.}",
          { I: [9, "B takes the chosen feature further into an effect on the reader."] }],
        ["A", "{I|Yeah, and it's kind of a promise that the whole book's going to be like this.}",
          { I: [7, "A adds the consequence for the rest of the novel."] }],
        ["B", "{P|clearly, for the write-up} Our one thing: the exact numbers show us the narrator before he tells us anything about himself.",
          { P: [8, "The one thing, said as a sentence the table can write down and the class can hear."] }],
      ] },
      { level: 10, band: "Above", lines: [
        ["A", "{P|reads evenly, then the first sentence again} {L|What's the first sentence doing before anything happens?}",
          { P: [9, "The re-read changes pace to suit the purpose: this sentence is the one to look at."],
            L: [9, "A opens with the question that makes the pair listen to the sentence rather than the plot."] }],
        ["B", "{I|It's giving us a time to the minute. '7 minutes after midnight' is more exact than anyone needs.}",
          { I: [7, "B points at the words and names what is odd about them."] }],
        ["A", "{I|Yes, and the sentences are all short after that. 'The dog was dead.' It's like a report.}",
          { I: [7, "'Yes, and' with a second feature and the sentence that shows it."] }],
        ["B", "{L|A report of what, though? Because he's also hugging the dog, and he doesn't say how that feels.}",
          { L: [9, "B pushes on A's word 'report' and tests it against what else is on the page."] }],
        ["A", "{L|So the writing is exact about facts and blank about feelings. That's the effect: we get the facts and have to guess the feeling.}",
          { L: [10, "A analyses the effect of the language on the reader. Discussing purposes and effects of language features is the level 10 line."] }],
        ["B", "{I|And that's on purpose, because it's how Christopher's head works. The style is the character.} {I|Do you want to take the one thing, or should I?}",
          { I: [9, "B builds on A to reach a claim about the novel, then shares the closing turn instead of taking it."] }],
        ["A", "You say it.", {}],
        ["B", "{P|clearly, for the class} Our one thing: exact facts, no feelings, so the style shows us Christopher before the plot does.",
          { P: [8, "One clear sentence, delivered for the class rather than for A."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads the first page aloud, then reads the first sentence again} {L|Before we do what happens, what's the first sentence doing?}",
          { P: [9, "Re-reading the sentence that matters changes the pace to suit the purpose."],
            L: [9, "A opens with the question that makes the pair listen to the sentence rather than the plot."] }],
        ["B", "{I|It's a time, to the exact minute, and it's the digit 7, not the word. He's counting before he's feeling anything.}",
          { I: [9, "B points at the smallest possible thing, a digit, and gives it a meaning."] }],
        ["A", "{I|Yes, and he keeps counting. 'Four moods', 'hugging the dog for 4 minutes'. The counting is a habit, and we'll see it the whole book.}",
          { I: [9, "'Yes, and' with two more numbers, then a link from the first sentence to the novel's method."] }],
        ["B", "{I|And it costs him something, on this page even. He can tell us the fork went through the dog but not what he felt about it. The only feeling word is 'I like dogs', and that comes after the blood.}",
          { I: [9, "B takes A's 'habit' further into its cost, and finds the one feeling word and its position."] }],
        ["A", "{L|So the calm isn't really calm?} {I|It's him not having a word for it yet, which isn't the same as not caring. That's the bit people get wrong the first time they read it.}",
          { L: [8, "A infers what B's point implies and checks it in three words."],
            I: [10, "A elaborates B's link into the distinction the pair will keep. Developing and clarifying thinking through discussion is the Listening 11 line."] }],
        ["B", "{I|So the numbers make us do the feeling for him. 'The dog was dead' is four words. We do the rest.}",
          { I: [9, "B elaborates to the reader's role and points at the sentence that proves it."] }],
        ["A", "{L|Can I push on 'we do the rest'?} {I|Because at the station later he gives us just numbers and signs again, and by then we read them as panic. Same trick, opposite feeling.}",
          { L: [9, "A asks for the turn by quoting B's words, then tests them against another passage."],
            I: [10, "The link runs across the whole book to show the technique changing its effect."] }],
        ["B", "{P|slowly, for the class} Our one thing: he's exact to the minute, so we have to supply the feeling, and the book teaches us which feeling as it goes.",
          { P: [9, "The pace changes for the audience: this sentence is for the class, not for A."] }],
      ] },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { SESSIONS };
