/* Table talk content. Two speakers, A and B. One session at a time, four
   positions: not working, level 7, level 9, level 11.

   Line shape: [speaker, text, notes]
     text   mark the words that count with {L|…} {I|…} {P|…}
            L = Listening, I = Interacting, P = Presenting (the three rubric rows)
     notes  { L: [level, why], I: [level, why], P: [level, why] }
            the level is the continuum level those words are evidence for,
            which is not always the level of the conversation. */

const SESSIONS = [
  {
    n: 1, title: "Personal response", label: "Session 1 · Table 4 · Chapter 37",
    prompt: "I do not tell lies. Mother used to say that this was because I was a good person. But it is not because I am a good person. It is because I can't tell lies.",
    task: "A feeling and a reason each. Then respond to each other.",
    levels: [
      { level: null, band: "Not working", lines: [
        ["A", "{P|reads}", { P: [5, "Reading aloud is the only speaking done, and it is done to get it over with."] }],
        ["B", "Yeah.", {}],
        ["A", "{I|I agree.}", { I: [5, "Agreement with nothing to agree with. No point of view has been given."] }],
        ["B", "It's like, deep.", {}],
        ["A", "What do we write?", {}],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the quote fast, eyes on the page} {I|I think that's good, he doesn't lie.}",
          { P: [5, "Read to the table, but fast and eyes down: nothing in the voice helps B hear the quote."],
            I: [5, "A point of view is given with no reason. 'Good' gives B nothing to answer."] }],
        ["B", "{I|Yeah, same.} Lying's bad.",
          { I: [5, "Agreement without a reason of its own. The talk is still where A left it."] }],
        ["A", "{I|Like, if you never lie people trust you.}",
          { I: [5, "Now a reason. A has presented and justified a point of view, which is level 5."] }],
        ["B", "{L|Wait, what do you mean by trust?}",
          { L: [5, "A clarifying question. It gets A to say what a word means, which is level 5 listening."] }],
        ["A", "Like they know you won't make stuff up.", {}],
        ["B", "Okay. {I|I still reckon it's a bit sad though, his mum said he's good and he's like, no I'm not.}",
          { I: [7, "An interpretation with a reason from the quote, shared into the discussion. This one line is level 7."] }],
        ["A", "{P|looks at the clock} Are we done?",
          { P: [6, "The body language says the talk is over. Two minutes in, because nobody built on B's idea."] }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads slowly, looks up at the end} {I|My first reaction is that it's a bit sad, because he's correcting his own mum: 'it is not because I am a good person'.}",
          { P: [7, "Slowing down and looking up at the end uses voice and body to hand the quote to B."],
            I: [7, "A feeling, a reason, and the words it comes from. This is what a shared interpretation looks like."] }],
        ["B", "{L|So you're reading it as him rejecting her?} {I|I found it funny, the way he splits hairs: good person versus 'can't tell lies'.}",
          { L: [8, "B says back what A implied but did not say, then checks it. Interpreting implied meaning is level 8."],
            I: [7, "B disagrees with the feeling, not with A, and gives the reason in the same breath."] }],
        ["A", "{L|Funny on purpose, or just funny to us?}",
          { L: [8, "A separates two meanings B ran together. The question sharpens B's idea rather than attacking it."] }],
        ["B", "To us. He's dead serious. {I|And that's what makes it a bit sad as well, so I partly agree with you.}",
          { I: [7, "B answers, then links back to A's feeling. Two responses have become one conversation."] }],
        ["A", "{I|I'd add that 'I can't' means he never has to decide. Honestly I'd find that easier.}",
          { I: [7, "A adds a new reading and links it to their own life. The link comes straight back to the quote."] }],
        ["B", "{L|Say more about 'easier'?}",
          { L: [7, "Active listening: B keeps A's best idea alive by asking for more instead of moving on."] }],
        ["A", "We lie to be polite. He'd just tell you the true thing about your haircut.", {}],
        ["B", "{I|I see it differently, because the stress just moves onto everyone else.} {P|pauses} So, a strength and a problem?",
          { I: [9, "Disagreement said as 'I see it differently, because'. The voice is changed to discuss, not to win."],
            P: [7, "The pause before the question gives A room to answer instead of filling the silence."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads it twice, the second time stressing 'can't'} {I|It lands as lonely: 'I can't' is the only reason he gives, and the mother's kinder version gets crossed out.}",
          { P: [9, "Re-reading with a different stress is a change of voice used to make an argument."],
            I: [7, "The reason is built from a single stressed word and a contrast between two reasons in the quote."] }],
        ["B", "{L|So you're saying he'd rather be accurate than be thought of as good?}",
          { L: [8, "B paraphrases A's idea back as a question to test it. Inferring what A implies, then checking."] }],
        ["A", "Yes. Right about himself rather than liked.", {}],
        ["B", "{I|I'd push back. He isn't rejecting 'good'; he just can't accept a reason that isn't true. Which is the most honest line in the book.}",
          { I: [9, "B disagrees with A's reading, not A's feeling, and offers a rival reading of the same words."] }],
        ["A", "{L|Where does that leave the white lies?} {I|Later he says a white lie only leaves things out, and he's fine with that. So the rule isn't as pure as it sounds.}",
          { L: [9, "A listens critically: B's claim is tested against a second passage, not just accepted."],
            I: [7, "A counters with evidence from another part of the novel."] }],
        ["B", "{L|Which chapter, roughly?}",
          { L: [9, "B asks for the location so the evidence can be checked, not taken on trust."] }],
        ["A", "Straight after this one, 37, is the definition. The white-lie bit comes a few chapters on. {P|reads two lines}",
          { P: [8, "Reading the lines aloud puts the evidence in front of B clearly enough to argue with."] }],
        ["B", "{I|Okay, that changes my view: 'leaving things out' is exactly what Father does about Mother, so Christopher's own rule lets in the biggest lie in the book.} {P|slows right down for the last sentence} Shall we put that down as our one thing?",
          { I: [10, "B revises out loud and turns the talk into a shared product. Building on and refining ideas in response to a peer is the Listening 11 line too."],
            P: [9, "Slowing down for the sentence that matters suits the purpose: this is the line to write down."] }],
      ] },
    ],
  },

  {
    n: 2, title: "I couldn't disagree more", label: "Session 2 · Table 1",
    prompt: "Ed Boone is a good father.",
    task: "Take a side with a reason from the book. Quote the other person back before you answer them.",
    levels: [
      { level: null, band: "Not working", lines: [
        ["A", "{P|reads the statement}", { P: [5, "Read, and then nobody takes a side."] }],
        ["B", "Nah.", {}],
        ["A", "Yeah he's bad.", {}],
        ["B", "{P|shrugs}", { P: [5, "A shrug is the whole contribution."] }],
        ["A", "So, disagree?", {}],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the statement} {I|No way. He killed the dog.}",
          { P: [6, "Read clearly enough for B to answer."],
            I: [5, "A side and a reason in five words. It is a start."] }],
        ["B", "{I|I dunno, he does look after him though.}",
          { I: [5, "A different side with a reason, but 'looks after' is vague. A cannot quote it back because there is nothing specific in it."] }],
        ["A", "But he killed a dog with a garden fork!",
          { }],
        ["B", "{L|Yeah but that's one thing.}",
          { L: [6, "B has heard A's key idea and repeats it, but does not say what it weighs against."] }],
        ["A", "{I|It's a big thing.}",
          { I: [5, "A repeats their own point louder instead of answering B's. Nobody has quoted anyone."] }],
        ["B", "{P|shrugs} I guess.",
          { P: [6, "B gives up a real position with body language, because nobody asked for the evidence behind it."] }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads the statement, looks up} {I|I couldn't disagree more. He killed a dog with a garden fork and told his son the mother was dead.}",
          { P: [7, "Looking up after the statement invites the answer."],
            I: [7, "A side and two reasons from the book in one breath."] }],
        ["B", "{I|I'm going to agree, and I know that sounds bad. He cooks, he gets Christopher to school, he goes to the police station at one in the morning. The lie is terrible but the daily stuff is good fathering.}",
          { I: [7, "B takes the harder side and backs it with three concrete moments."] }],
        ["A", "{L|Do you mean good father overall, or good at the daily stuff? Because those aren't the same.}",
          { L: [8, "A splits 'good father' into two meanings B had run together. The argument now has somewhere to go."] }],
        ["B", "{I|Fair. Good at the daily stuff, and I think that counts for more than one lie.}",
          { I: [9, "B concedes the distinction and restates the position inside it. Conceding is a change of voice, not a loss."] }],
        ["A", "{L|You said 'one lie'.} {I|It's not one lie, it's every day for two years. 'Your mother is dead', every day.}",
          { L: [9, "A quotes B's exact words back before answering them. That is critical listening: the answer is to what was actually said."],
            I: [7, "The counter is specific: the scale of the lie, in the book's own words."] }],
        ["B", "{I|Somewhere in the middle then. The 'you have to learn to trust me' scene is him trying,} {P|steady, not louder} but you can't order someone to trust you.",
          { I: [7, "B moves to a middle position and supports it with a line from the book."],
            P: [7, "The voice stays steady while disagreeing; volume is not the argument."] }],
        ["A", "{I|I'd sign 'a loving father who did something unforgivable'. Is that allowed as an answer?}",
          { I: [9, "A revises openly and offers a shared wording. The talk ends with a position, not a winner."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads the statement} {L|Before sides: what would count as evidence either way?}",
          { P: [8, "Read clearly to the table, then the floor is opened rather than filled."],
            L: [9, "A asks the pair to agree what would settle the question before anyone argues it."] }],
        ["B", "{I|Actions towards Christopher, over time. Not intentions. On that test he fails, because the two-year lie is an action every single day.}",
          { I: [9, "B sets the test, then applies it. The side comes with the standard it was judged by."] }],
        ["A", "{L|'Actions over time' is my test too,} {I|and the actions over time also include cooking, school runs, the police station at 1 a.m., the swimming. So the real question is whether one enormous action cancels a thousand small ones.}",
          { L: [9, "A quotes B's test back and accepts it before disagreeing about what it shows."],
            I: [10, "A reframes the statement as a weighing problem the pair can actually decide. This is the Listening 10 line: analysing the purpose of the question."] }],
        ["B", "{I|I'll give you the thousand small ones. But the small ones are what a carer does, and the big one is what only a liar does.}",
          { I: [9, "B concedes the whole of A's evidence and still counters, by changing what kind of thing each action is."] }],
        ["A", "{L|'Carer versus liar' assumes he can only be one.} {I|The confession has him being both in one speech: 'I did it for the best' and 'I killed Wellington' are about ten lines apart.}",
          { L: [9, "A quotes B's phrase and names the assumption inside it."],
            I: [7, "The counter is the passage that shows both things at once, located by its distance between two lines."] }],
        ["B", "{I|Okay, he's both. Then 'good father' is the wrong question, and the real one is whether Christopher can ever trust him again, which is what the last chapters are actually about.}",
          { I: [10, "B concedes the reading and reframes toward the question the novel itself asks. Refining an idea in response to a peer is the Listening 12 line."] }],
        ["A", "{I|On that question the ending says he can do anything. It doesn't say he trusts Father. Those aren't the same.} {P|lets that sit}",
          { I: [9, "A checks the shared position against the exact wording of the ending."],
            P: [9, "Silence used on purpose: the pause gives the last point its weight."] }],
        ["B", "Not a good father, possibly a recoverable one. {L|Would you sign that?}",
          { L: [9, "B states the shared position and checks it is shared before it goes in the write-up."] }],
      ] },
    ],
  },

  {
    n: 3, title: "Passage analysis panel", label: "Session 3 · Table 1 · Chapter 2",
    prompt: "The opening: 'It was 7 minutes after midnight.' Christopher finds Wellington.",
    task: "What happens, how it is written, what it shows. Say 'yes, and'. Finish with the one thing you would tell the class.",
    levels: [
      { level: null, band: "Not working", lines: [
        ["A", "{P|reads the first page}", { P: [5, "The reading is done, and then nobody claims the first turn."] }],
        ["B", "So the dog's dead.", {}],
        ["A", "Yeah.", {}],
        ["B", "What do we write for the writing bit?", {}],
        ["A", "Dunno. Short sentences?", {}],
      ] },
      { level: 7, band: "Working towards", lines: [
        ["A", "{P|reads the first page, quickly} So he finds the dog and it's dead.",
          { P: [5, "Read to the table, but too fast for B to hear the sentences as sentences."] }],
        ["B", "{I|It says '7 minutes after midnight'. That's weird.}",
          { I: [5, "B points at words on the page and gives an opinion about them. 'Weird' is the start of a feature, not a description of one."] }],
        ["A", "{L|Yeah, it's like really specific.}",
          { L: [6, "A has heard B's key idea and nearly names the feature. 'Specific' needs a second sentence that never comes."] }],
        ["B", "And the dog's got a fork in it.", {}],
        ["A", "What do we write for the writing bit?", {}],
        ["B", "{I|Um, short sentences?}",
          { I: [5, "A real feature, guessed rather than pointed at. Nobody finds one."] }],
        ["A", "Okay, short sentences.",
          { }],
      ] },
      { level: 9, band: "Expected", lines: [
        ["A", "{P|reads the first page aloud, evenly} What happens is simple: he finds the dog, it's dead, there's a fork through it. {I|What's odd is how calm it is.}",
          { P: [7, "Reading evenly lets the flat tone of the page show. The voice is doing the analysis before the words do."],
            I: [7, "A answers the first panel question and offers the first feature for B to pick up."] }],
        ["B", "{L|Calm how? What makes it calm?}",
          { L: [7, "B refuses a vague word and asks A to say what makes it so. Active listening that improves the other person's idea."] }],
        ["A", "{I|'7 minutes after midnight', not 'just after midnight'. And the sentences are all short: 'The dog was dead.' Full stop.}",
          { I: [7, "A points at two things on the page: a number and a sentence length."] }],
        ["B", "{I|Yes, and there are no feeling words at all. He says the dog 'was not running or asleep', like he's ruling things out.}",
          { I: [7, "'Yes, and': B accepts A's features and adds a third, with its own quotation."] }],
        ["A", "{L|So the feature is short sentences plus exact numbers plus no emotion? That's three things. Do we pick one?}",
          { L: [8, "A joins the three observations into one claim and asks B to choose. Summarising what was said is listening for key ideas."] }],
        ["B", "{I|The numbers. Because '7 minutes' is the first thing on the page, it tells you how this narrator's head works before you know his name.}",
          { I: [9, "B takes the chosen feature further into an effect on the reader."] }],
        ["A", "{I|Agree, and it's a promise: the whole book is going to be like this.}",
          { I: [7, "A adds the consequence for the rest of the novel."] }],
        ["B", "{P|clearly, for the write-up} Our one thing: the exact numbers show us the narrator before he tells us anything about himself.",
          { P: [8, "The one thing, said as a sentence the table can write down and the class can hear."] }],
      ] },
      { level: 11, band: "Above", lines: [
        ["A", "{P|reads the first page aloud, then reads the first sentence again} {L|Before 'what happens': what is the first sentence doing?}",
          { P: [9, "Re-reading the sentence that matters changes the pace to suit the purpose."],
            L: [9, "A opens with the question that makes the pair listen to the sentence rather than the plot."] }],
        ["B", "{I|It's a time, to the minute, as a digit: '7', not 'seven'. He counts before he feels.}",
          { I: [9, "B points at the smallest possible thing, a digit, and gives it a meaning."] }],
        ["A", "{I|Yes, and the counting continues: 'four moods', 'hugging the dog for 4 minutes'. So the number isn't a detail, it's a habit we're going to watch for the whole book.}",
          { I: [9, "'Yes, and' with two more numbers, then a link from the first sentence to the novel's method."] }],
        ["B", "{I|And the habit has a cost, which is on this page too: he can tell us the fork went through the dog but not what he felt about it. The only feeling word is 'I like dogs', and it comes after the blood.}",
          { I: [9, "B takes A's 'habit' further into its cost, and finds the one feeling word and its position."] }],
        ["A", "{L|So the calm isn't calm?} {I|It's the narrator not having a word yet, which is different from not caring. That's what a first-time reader gets wrong.}",
          { L: [8, "A infers what B's point implies and checks it in three words."],
            I: [10, "A elaborates B's link into the distinction the pair will keep. Developing and clarifying thinking through discussion is the Listening 11 line."] }],
        ["B", "{I|So the effect of the numbers is that the reader supplies the feeling. 'The dog was dead' is four words; we do the rest.}",
          { I: [9, "B elaborates to the reader's role and points at the sentence that proves it."] }],
        ["A", "{L|Can I push on 'we do the rest'?} {I|Because at the station he also gives us just numbers and signs, and by then we've learned to read them as panic. Same technique, opposite feeling.}",
          { L: [9, "A asks for the turn by quoting B's words, then tests them against another passage."],
            I: [10, "The link runs across the whole book to show the technique changing its effect."] }],
        ["B", "{P|slowly, for the class} Our one thing: precision to the minute makes the reader supply the feeling, and the book teaches us which feeling as it goes.",
          { P: [9, "The pace changes for the audience: this sentence is for the class, not for A."] }],
      ] },
    ],
  },
];

if (typeof module !== "undefined") module.exports = { SESSIONS };
